FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir paho-mqtt pyserial requests

COPY app/bridge.py .
COPY app/vertical_home.py /app/vertical_home.py
CMD ["python", "./bridge.py"]
