; firmware/platformio.ini

[platformio]
default_envs = encoder-mux-esp32
src_dir = .

[env:encoder-mux-esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<encoder_mux.cpp>
build_flags =
  -I include