#####################################################################
# /home/pi/printer_data/config/crowsnest.conf (example path)
#####################################################################

[crowsnest]
log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false

[cam 1]
mode: ustreamer
port: 8080 #change later
device: /dev/v4l/by-id/usb-ARDUCAM_<your-first-camera>-video-index0
resolution: 1280x720
max_fps: 20

[cam 2]
mode: ustreamer
port: 8081 # change later
device: /dev/v4l/by-id/usb-ARDUCAM_<your-second-camera>-video-index0
resolution: 1280x720
max_fps: 15